# -*- coding: utf-8 -*-
"""webscrapping

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1to4BIMrGmJM5kIjkgKM0J7fF-gI9eE__
"""



from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_India"

table=soup.find_all("table")[1]

page = requests.get(url)
soup= BeautifulSoup(page.text, 'html')

print(table)

world_titles =table.find_all("th")

print (world_titles)

world_titles_table =[title.text.strip() for title in world_titles]

print (world_titles_table)

df = pd.DataFrame(columns=world_titles_table)

df

import pandas as pd

df = pd.DataFrame(columns  =world_titles_table)
df

column_data = table.find_all("tr")

for row in column_data[1:]:
  row_data =row.find_all("td")
  individual_row_data = [data.text.strip() for data in row_data]
  print(individual_row_data)
  length = len(df)
  df.loc[length]=individual_row_data

df

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

# @title State Controlled

from matplotlib import pyplot as plt
import seaborn as sns
df.groupby('State Controlled').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)